import{a as R,S,i}from"./assets/vendor-xpOxgMII.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",M="54492402-008c237b79b4e7660b85c858e",$=15;async function m(r,o){var s,a,e;try{return(await R.get(v,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:$}})).data}catch(t){const n=((a=(s=t==null?void 0:t.response)==null?void 0:s.data)==null?void 0:a.message)||((e=t==null?void 0:t.response)==null?void 0:e.data)||t.message||"Request failed";throw new Error(n)}}const g=document.querySelector(".gallery"),h=document.querySelector(".loader-wrap"),p=document.querySelector(".load-more"),B=new S(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const o=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:n,comments:E,downloads:P})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${t}</p>
            <p class="info-item"><b>Views</b> ${n}</p>
            <p class="info-item"><b>Comments</b> ${E}</p>
            <p class="info-item"><b>Downloads</b> ${P}</p>
          </div>
        </li>
      `).join("");g.insertAdjacentHTML("beforeend",o),B.refresh()}function A(){g.innerHTML=""}function b(){h.hidden=!1}function u(){h.hidden=!0}function L(){p.hidden=!1}function c(){p.hidden=!0}const q=document.querySelector(".form"),O=document.querySelector(".load-more");let d="",l=1,f=0;const w=15;q.addEventListener("submit",_);O.addEventListener("click",x);u();c();async function _(r){r.preventDefault();const o=r.currentTarget.elements["search-text"].value.trim();if(!o){u(),c(),i.warning({message:"Please enter a search query.",position:"topRight"});return}d=o,l=1,A(),c(),b();try{const s=await m(d,l);f=s.totalHits;const a=s.hits;if(!a||a.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(a);const e=Math.ceil(f/w);l<e?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){i.error({message:s.message||"Request failed. Please try again.",position:"topRight"})}finally{u(),q.reset()}}async function x(){l+=1,c(),b();try{const o=(await m(d,l)).hits;if(!o||o.length===0){i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}y(o),G();const s=Math.ceil(f/w);l<s?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){i.error({message:r.message||"Request failed. Please try again.",position:"topRight"})}finally{u()}}function G(){const r=document.querySelector(".gallery-item");if(!r)return;const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
